export enum EnergySavingLevels {
  auto = 'auto',
  screenOff = 'screenoff',
  maximum = 'maximum',
  medium = 'medium',
  minimum = 'minimum',
  off = 'off',
}

export enum Inputs {
  dtv = 'dtv',
  atv = 'atv',
  cadtv = 'cadtv',
  catv = 'catv',
  av = 'avav1',
  component = 'component1',
  hdmi1 = 'hdmi1',
  hdmi2 = 'hdmi2',
  hdmi3 = 'hdmi3',
  hdmi4 = 'hdmi4',
}

export enum Keys {
  arrowDown = 'arrowdown',
  arrowLeft = 'arrowleft',
  arrowRight = 'arrowright',
  arrowUp = 'arrowup',
  aspectRatio = 'aspectratio',
  audioMode = 'audiomode',
  back = 'returnback',
  blueButton = 'bluebutton',
  captionSubtitle = 'captionsubtitle',
  channelDown = 'channeldown',
  channelList = 'channellist',
  channelUp = 'channelup',
  deviceInput = 'deviceinput',
  energySaving = 'screenbright',
  fastForward = 'fastforward',
  greenButton = 'greenbutton',
  home = 'myapp',
  info = 'programminfo',
  liveTV = 'livetv',
  menu = 'settingmenu',
  number0 = 'number0',
  number1 = 'number1',
  number2 = 'number2',
  number3 = 'number3',
  number4 = 'number4',
  number5 = 'number5',
  number6 = 'number6',
  number7 = 'number7',
  number8 = 'number8',
  number9 = 'number9',
  ok = 'ok',
  play = 'play',
  previousChannel = 'previouschannel',
  programGuide = 'programguide',
  record = 'record',
  redButton = 'redbutton',
  rewind = 'rewind',
  sleepTimer = 'sleepreserve',
  userGuide = 'userguide',
  videoMode = 'videomode',
  volumeDown = 'volumedown',
  volumeMute = 'volumemute',
  volumeUp = 'volumeup',
  yellowButton = 'yellowbutton',
}
